# Generated by Django 2.1.7 on 2020-12-17 12:39

from django.db import migrations, models
import django.db.models.deletion
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Gr33kLibrary', '0005_update_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tags', models.CharField(max_length=255, null=True)),
                ('content', mdeditor.fields.MDTextField()),
                ('title', models.CharField(max_length=255)),
                ('create_time', models.DateTimeField(auto_now=True)),
                ('update_time', models.DateTimeField(null=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Gr33kLibrary.User')),
                ('classify', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Gr33kLibrary.Classify')),
            ],
        ),
    ]
