# Generated by Django 2.1.7 on 2020-12-17 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gr33kLibrary', '0009_tool'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='create_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
