# Generated by Django 2.1.7 on 2020-12-17 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gr33kLibrary', '0011_tool_upload_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='file_size',
            field=models.IntegerField(default=0),
        ),
    ]
