# Generated by Django 2.1.7 on 2020-12-17 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gr33kLibrary', '0012_tool_file_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='file_size',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
