# Generated by Django 2.1.7 on 2020-12-18 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gr33kLibrary', '0013_auto_20201217_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='invitation_code',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
