# Generated by Django 2.1.7 on 2020-12-18 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gr33kLibrary', '0014_auto_20201218_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='invitation_num',
            field=models.IntegerField(default=0),
        ),
    ]
