# Generated by Django 2.1.7 on 2020-12-19 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gr33kLibrary', '0015_user_invitation_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='read_num',
            field=models.IntegerField(default=0),
        ),
    ]
