# Generated by Django 2.1.7 on 2020-12-20 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gr33kLibrary', '0017_article_back_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='article_num',
            field=models.IntegerField(default=0),
        ),
    ]
