# Generated by Django 2.1.7 on 2020-12-20 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gr33kLibrary', '0018_user_article_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='type',
            field=models.IntegerField(default=0),
        ),
    ]
