# Generated by Django 2.1.7 on 2020-12-20 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gr33kLibrary', '0019_article_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_link',
            field=models.TextField(default=''),
        ),
    ]
