# Generated by Django 2.1.7 on 2020-12-22 01:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Gr33kLibrary', '0021_auto_20201220_1506'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collect',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(auto_now=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gr33kLibrary.Article')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gr33kLibrary.User')),
            ],
        ),
    ]
